### Suspense

탄스택 쿼리는 리액트의 Suspense를 위한 API도 제공함!!

- useSuspenseQuery
- useSuspenseInfiniteQuery
- useSuspenseQueries
- 추가로 useQuery().promise, React.use()도 제공함(실험중)

Suspense 모드를 사용할 때, status 상태나 에러객체는 필요하지 않다. React.Suspense(fallback, error boundary)컴포넌트 사용하면 저 기능들을 대체해줌

**throwOnError 옵션**

throwOnError 옵션은 쿼리가 실패했을 때 에러를 에러 바운더리로 던지는 옵션.

기본 값은 아래와 같이 false며, 에러가 발생해도 에러 바운더리로 전달 되지 않음. 따라서 isError 같은 속성으로 예외처리를 직접 해줘야 함

```js
const { data, error, isError } = useQuery({
  queryKey: ['todos'],
  queryFn: fetchTodos,
});

if (isError) console.error(error);
```

그래서 아래와 같이 throwOnError 옵션을 true로 변경하면 에러 바운더리에서 자동으로 에러를 던져줌

```js
const { data, error, isError } = useQuery({
  queryKey: ['todos'],
  queryFn: fetchTodos,
  throwOnError: true,
});
```

하지만 .... 내가 아래처럼 Suspense를 사용중이라면 ?

```js
useQuery({
  queryKey,
  queryFn,
  suspense: true, // suspense를 사용하거나
});

useSuspenseQuery({ queryKey, queryFn }); // useSuspenseQuery훅을 사용
```

이 경우 throwOnError은 직접 변경할 수 없으며 항상 다음과 같이 동작한다.

```js
throwOnError: (error, query) => typeof query.state.data === 'undefined';
```

이 속성은 모든 에러를 가장 가까운 에러 바운더리로 던지지 않는다. 오직 보여줄 데이터가 없을 경우에만 에러를 던진다.
즉, 쿼리가 성공한 적이 있어 캐시에 데이터가 들어있으면, 그 데이터가 오래되었더라도 컴포넌트를 렌더링함

왜 직접 변경할 수 없을까 ?

- suspense에서 에러를 던지면, 에러는 무조건 에러바운더리에 걸림
- 근데 캐시에 데이터가 있다면 ? 굳이 fallback ui를 보여줄 필요 없이 일단 stale 데이터 보여주면 됨
- 근데 에러 발생했으니 에러바운더리까지 전파시켜서 에러 fallback이 보여짐
- 비효율적이기 때문에 Suspense에서의 throwOnError 옵션은 개발자가 변경할 수 없고 항상 `(error, query) => typeof query.state.data === 'undefined'` 로 동작하도록 함

그래서 모든 에러를 에러바운더리로 다루려면 에러를 수동으로 전달해야 한다.

```js
import { useSuspenseQuery } from '@tanstack/react-query';

const { data, error, isFetching } = useSuspenseQuery({ queryKey, queryFn });

// suspense시 에러를 에러 바운더리로 보내고 싶을 땐 수동으로 던지기
if (error && !isFetching) {
  throw error;
}

// continue rendering data
```

**Suspense 모드를 설정하는 방법 1) Resetting Error Boundaries(에러바운더리 초기화)**

일반 쿼리에서 suspense나 throwOnError를 사용할 때,에러가 발생한 후 리렌더링할 때, 다시 시도중이라는 것을 쿼리가 알게할 방법이 필요하다.

쿼리 에러는 QueryErrorResetBoundary 컴포넌트나 useQueryErrorResetBoundary 훅을 통해 리셋할 수 있다.

```js
// QueryErrorResetBoundary 컴포넌트를 사용하는 방법
// 바운더리 내의 모든 에러가 리셋됨

import { QueryErrorResetBoundary } from '@tanstack/react-query';
import { ErrorBoundary } from 'react-error-boundary';

const App = () => (
  <QueryErrorResetBoundary>
    {({ reset }) => (
      <ErrorBoundary
        onReset={reset}
        fallbackRender={({ resetErrorBoundary }) => (
          <div>
            There was an error!
            <Button onClick={() => resetErrorBoundary()}>Try again</Button>
          </div>
        )}
      >
        <Page />
      </ErrorBoundary>
    )}
  </QueryErrorResetBoundary>
);
```

```js
// useQueryErrorResetBoundary 훅틀 사용하는 방법
// 이 경우 가장 가까운 에러바운더리 내에서 초기화 되고,
// 가장 가까운 에러바운더리가 없다면 전역에서 초기화 됨

import { useQueryErrorResetBoundary } from '@tanstack/react-query';
import { ErrorBoundary } from 'react-error-boundary';

const App = () => {
  const { reset } = useQueryErrorResetBoundary();
  return (
    <ErrorBoundary
      onReset={reset}
      fallbackRender={({ resetErrorBoundary }) => (
        <div>
          There was an error!
          <Button onClick={() => resetErrorBoundary()}>Try again</Button>
        </div>
      )}
    >
      <Page />
    </ErrorBoundary>
  );
};
```
